modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "voidbound"
version = "${file.jarVersion}"
displayName = "Voidbound"
logoFile = "voidbound.png"
authors = "mrsterner"
description = '''
Forge Template with ParchmentMC, KotlinForForge and Mixin
'''

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"